apiVersion: batch/v1
kind: Job
metadata:
  name: dailt
  namespace: evgeny
spec:
  template:
    metadata:
      labels:
        app: daily
    spec:
      containers:
      - name: my-container
        image: evgenyniko/scraping_project-daily:1.0.0
        envFrom:
        - configMapRef:
            name: app-env
        env:
        - name: DISCORD_URL
          value: "https://discord.com/api/webhooks/1253329204490010724/FncREuKLNeyutXZBdu28ZIDEoTFiWWImBdKfnoiNMF2D2goegLetwW7JmZBw_hEr-Ft4"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SASL_PASS
          valueFrom:
            secretKeyRef:
              key: client-passwords
              name: my-kafka-user-passwords
      restartPolicy: Never
  backoffLimit: 0
