apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scraping-app.fullname" . }}-backend
  labels:
    {{- include "scraping-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
    {{- include "scraping-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backend
      {{- include "scraping-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy | quote }}
          env:
            - name: SASL_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.env.kafkaSASL.key }}
                  name: {{ .Values.env.kafkaSASL.name }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONGO_USER
              value: {{ quote .Values.env.mongoUser }}
            - name: MONGO_HOST
              value: {{ quote .Values.env.mongoHost }}
            - name: MONGO_PORT
              value: {{ quote .Values.env.mongoPort }}
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.env.mongoPass.key }}
                  name: {{ .Values.env.mongoPass.name }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - configMapRef:
                name: app-env
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scraping-app.fullname" . }}-backend
  labels:
    {{- include "scraping-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: backend
    {{- include "scraping-app.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.backend.ports | toYaml | nindent 2 }}
