apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: evgeny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.2.2
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:29092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://broker:29092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: CONFLUENT_SUPPORT_CUSTOMER_ID
          value: "anonymous"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: evgeny
spec:
  ports:
  - name: port-9092
    port: 9092
    targetPort: 9092
  - name: port-29092
    port: 29092
    targetPort: 29092
  selector:
    app: broker
  type: ClusterIP
