apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy
  namespace: evgeny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-proxy
  template:
    metadata:
      labels:
        app: rest-proxy
    spec:
      containers:
      - name: rest-proxy
        image: confluentinc/cp-kafka-rest:7.2.2
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_REST_HOST_NAME
          value: "rest-proxy"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "broker:29092"
        - name: KAFKA_REST_LISTENERS
          value: "http://0.0.0.0:8082"
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: rest-proxy
  namespace: evgeny
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: rest-proxy
