appEnv:
  kafkaProducers:
    - kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local
    - kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local
    - kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local
  kafkaConsumer: kafka.kafka.svc.cluster.local:9092
  kafkaPort: "9092"
  saslUser: user1

env:
  mongoHost: mongo-mongodb.mongodb.svc.cluster.local
  mongoPort: "27017"
  mongoUser: root
  mongoPass:
    key: mongodb-root-password
    name: mongo-mongodb
  kafkaSASL:
    key: client-passwords
    name: kafka-user-passwords

backend:
  name: backend
  image:
    repository: evgenyniko/scraping_project-backend
    tag: 1.0.0
  targetPort: 5000
  imagePullPolicy: Always
  ports:
  - nodePort: 30015
    port: 5000
    protocol: TCP
    targetPort: 5000
  replicas: 1
  type: NodePort

frontend:
  name: frontend
  image:
    repository: evgenyniko/scraping_project-frontend
    tag: 1.0.0
  targetPort: 5000
  imagePullPolicy: Always
  ports:
  - nodePort: 30019
    port: 5000
    protocol: TCP
    targetPort: 5000
  replicas: 1
  type: NodePort

kubernetesClusterDomain: cluster.local
