live:
  backoffLimit: 0
  ttlSecondsAfterFinished: 20
  image:
    repository: evgenyniko/scraping_project-live
    tag: 1.0.0
  imagePullPolicy: Always

env:
  discordUrl: https://discord.com/api/webhooks/1253329204490010724/FncREuKLNeyutXZBdu28ZIDEoTFiWWImBdKfnoiNMF2D2goegLetwW7JmZBw_hEr-Ft4
  kafkaSASL:
    key: client-passwords
    name: kafka-user-passwords

kubernetesClusterDomain: cluster.local